### ISSUE TITLE
Sometimes the connection to the VictronEnergy Device is not possible 

### ISSUE THREAD

**Issue by lampep** [Nature40/tRackIT-OS#14]
2023-02-20 16:22:10.258601 INFO:smartsolar:Connecting to nearest VEDevice
2023-02-20 16:22:15.821099 INFO:smartsolar:[e7:96:b4:4f:83:43] Discovered VictronEnergy device "E7-96-B4-4F-83-43", RSSI: -51
2023-02-20 16:22:15.848886 INFO:smartsolar:[e7:96:b4:4f:83:43] Selected nearest device "E7-96-B4-4F-83-43"
2023-02-20 16:22:15.855310 INFO:smartsolar:Creating VictronEnergy pairing agent
2023-02-20 16:22:16.366205 ERROR:smartsolar:[e7:96:b4:4f:83:43] Pairing failed, rasing RuntimeError.
2023-02-20 16:22:16.370724 INFO:smartsolar:Querying finished.
2023-02-20 16:22:16.372194 WARNING:mqttutil:Task [smartsolar] failed:
2023-02-20 16:22:16.379578 ERROR:mqttutil:("Pairing VictronEnergy Device '%s' [%s] failed.", dbus.String('E7-96-B4-4F-83-43', variant_level=1), 'e7:96:b4:4f:83:43')
2023-02-20 16:22:16.379578 Traceback (most recent call last):
2023-02-20 16:22:16.379578   File "/home/pi/pymqttutil/mqttutil/__main__.py", line 131, in run
2023-02-20 16:22:16.379578     result = self._eval()
2023-02-20 16:22:16.379578   File "/home/pi/pymqttutil/mqttutil/__main__.py", line 80, in _eval
2023-02-20 16:22:16.379578     result = eval(self.func_str)
2023-02-20 16:22:16.379578   File "<string>", line 1, in <module>
2023-02-20 16:22:16.379578   File "/home/pi/pysmartsolar/smartsolar/__init__.py", line 423, in read_nearest_vedevice
2023-02-20 16:22:16.379578     d = manager.connect_nearest_vedevice(discovery_duration, passkey=passkey)
2023-02-20 16:22:16.379578   File "/home/pi/pysmartsolar/smartsolar/__init__.py", line 406, in connect_nearest_vedevice
2023-02-20 16:22:16.379578     raise RuntimeError("Pairing VictronEnergy Device '%s' [%s] failed.", d.alias(), d.mac_address)
2023-02-20 16:22:16.379578 RuntimeError: ("Pairing VictronEnergy Device '%s' [%s] failed.", dbus.String('E7-96-B4-4F-83-43', variant_level=1), 'e7:96:b4:4f:83:43')

**Comment by jonashoechst** [comment]
As the error belongs to the specific SmartSolar client implemention, I'd ask you to open the issue here: https://github.com/tRackIT-Systems/pysmartsolar/tree/main
